ci:
    autofix_prs: false
repos:
  - repo: https://github.com/tsvikas/sync-with-uv
    rev: v0.4.0
    hooks:
      - id: sync-with-uv
  - repo: local
    hooks:
      # Prevent committing .rej files from copier
      - id: forbidden-copier-rej-files
        name: forbidden copier rej files
        entry: found Copier update rejection files; review them and remove them
        language: fail
        files: \.rej$
  - repo: local
    hooks:
      # Prevent committing test.py files within the tests directory
      - id: forbidden-testpy-files
        name: forbidden testpy files
        entry: found test.py file inside tests directory; rename or remove them
        language: fail
        files: ((./tests/.*/test.py)|(./tests/test.py))$
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.13
    hooks:
      - id: uv-lock
      - id: uv-sync
      - id: uv-export
        args: ["--quiet"]
      - id: uv-export
        args: ["--frozen", "--no-group=dev", "--no-group=test", "--output-file=docs/requirements.txt", "--quiet"]
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.11.1
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/python-formate/flake8-dunder-all
    rev: v0.5.0
    hooks:
      - id: ensure-dunder-all
        files: .*/__init__\.py$
        exclude: tests/assets/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: ["--fix", "--ignore", "FIX"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=100000]
      - id: trailing-whitespace
        exclude: (.*\.sh|.*\.d2|.*\.md|.*\.drawio|.*egg-info.*|)$
      - id: check-merge-conflict
        args: [--assume-in-merge]
  - repo: local
    hooks:
      - id: deptry
        name: deptry
        entry: uv run --frozen --offline deptry src
        language: system
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: import-linter
        name: import-linter
        entry: uv run --frozen --offline lint-imports
        language: system
        always_run: true
        pass_filenames: false
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
default_install_hook_types:
  - pre-commit
  - pre-push
  - post-checkout
  - post-merge
  - post-rewrite
default_stages:
  - pre-commit
  - pre-push
